### ISSUE TITLE
Mise en place d'un sous domaine pour le site

### ISSUE THREAD

**Issue by florinesueur** [cnumr/best-practices-wordpress#53]
### Discussed in https://github.com/cnumr/fiches-wordpress-greenit/discussions/43

- [ ] Choisir un sous-domaine
- [ ] Demander le sous domaine à l'asso
- [ ] Transmettre les DNS à l'asso
- [ ] Vérification de la propagation

**Comment by bordage** [comment]
Bonjour tout le monde. On héberge tout sur le domaine greenit.fr et c'est moi qui ai la maîtrise du DNS. A votre dispo pour ajouter le sous domaine de votre choix.
